### PR TITLE
fix: macos require path error

### PR DESCRIPTION
**Pull request by sccgithub**

### CODE REVIEW

**Comment by fi3ework** [comment]
@sccgithub Thanks for the PR. Could you describe how to contrive an error without this PR for more context?

**Comment by sccgithub** [comment]
> Thanks for the PR. Could you describe how to contrive an error without this PR for more context

When I use this plugin under macOS, the error "Error: Cannot find module'./checkers/typescript/main'" will be reported.
So I changed the code of dynamically importing files to make it more robust.

**Comment by fi3ework** [comment]
@sccgithub Weird. I use macOS too and I never encounter this issue. 🤔

**Comment by fi3ework** [comment]
And as described in Nodejs documentation https://nodejs.org/api/modules.html#modules_require_id

**Comment by sccgithub** [comment]
> @sccgithub Weird. I use macOS too and I haven't encountered this issue ever. 🤔

I found that the old version of the npm package was installed before, which caused the plug-in to be unavailable. After the updated version, there is no problem. 
The above require problem appeared yesterday when the project was cloned locally for debugging. This plugin was introduced locally across projects, similar to this "import checker from'../vite-plugin-checker/packages/vite-plugin-checker// lib/main'"

**Comment by fi3ework** [comment]
Emm, since `require './a.js'` acts as `require(__dirname, 'a.js')`, I'm going to close this PR unless there's a scenario that only the latter one works.

**Comment by sccgithub** [comment]
Yes, this is indeed a problem that can only be encountered when cross-project introduction, you can turn it off.

**Comment by fi3ework** [comment]
@sccgithub Actually I gave a try to the cross-project import. `require` also works fine. How I try:

file a.js has code: `require './b.js'`

and I run `node a.js` in another CWD. a.js successfully find b.js.

**Pull request closed without merging**
