### PR TITLE
add named export to improve `"module": "nodenext"` compatibility

### PR DESCRIPTION
**Pull request by wight554**
* currently it shows error:
This expression is not callable.
  Type 'typeof import("node_modules/vite-plugin-checker/lib/main")' has no call signatures.ts(2349)
* see https://github.com/microsoft/TypeScript/issues/48845

### CODE REVIEW

**Comment by wight554** [comment]
it's possible to follow [this](https://github.com/bendrucker/snakecase-keys/pull/72) example as an alternative but that requires deleting `isObject` export from main file (is it needed tho?)

**Comment by wight554** [comment]
@fi3ework any objections on merging this one?
Fixes this issue:
image

**Comment by fi3ework** [comment]
@wight554 thanks for the PR, I was wondering is there way to also use default export in ESM which will be aligned with CJS?

**Comment by wight554** [comment]
> @wight554 thanks for the PR, I was wondering is there way to also use default export in ESM which will be aligned with CJS?

Ideally `.d.ts` for CJS and `.d.mts` for ESM, so CJS file definition can have exported namespace, like in example.
But I think Typescript compiler doesn't create separate type definitions from `.ts` files

**Comment by fi3ework** [comment]
Does a conditional export works for this? https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#package-json-exports-imports-and-self-referencing ESM and CJS can use different types entries and we can build different types fils before publishing

**Comment by wight554** [comment]
> Does a conditional export works for this? https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#package-json-exports-imports-and-self-referencing ESM and CJS can use different types entries and we can build different types fils before publishing

Well having mjs typings requires mjs module, won't it be overhead ti to have 2 versions if plugin if it works as is?
It's just esm requires named cjs exports to work properly with cjs modules

**Comment by wight554** [comment]
@fi3ework added changes to make module cjs style, can you build and attach output `.d.ts` file?
Unfortunately I couldn't build command run successfully on 2 machines, always fails with:
```
CLI Building entry: src/Checker.ts, src/FileDiagnosticManager.ts, src/codeFrame.ts, src/logger.ts, src/main.ts, src/types.ts, src/worker.ts, src/client/index.ts, src/checkers/eslint/cli.ts, src/checkers/eslint/main.ts, src/checkers/eslint/options.ts, src/checkers/typescript/main.ts, src/checkers/vls/cli.ts, src/checkers/vls/diagnostics.ts, src/checkers/vls/initParams.ts, src/checkers/vls/main.ts, src/checkers/vls/typings.d.ts, src/checkers/vueTsc/main.ts, src/checkers/vueTsc/prepareVueTsc.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v5.12.3
CLI Using tsup config: /Users/Volodymyr_Zhdanov/playground/vite-plugin-checker/packages/vite-plugin-checker/tsup.config.ts
CLI Target: node12
CJS Build start
post-esbuild bundling patch failed
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by fi3ework** [comment]
I'm not sure if `export = plugin` is a valid ES syntax, if so, could you please paste a link for that?

**Comment by fi3ework** [comment]
I think the previous implementation is simple enough to handle the `nodenext` for now. 

> > Does a conditional export works for this? https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#package-json-exports-imports-and-self-referencing ESM and CJS can use different types entries and we can build different types fils before publishing
> 
> Well having mjs typings requires mjs module, won't it be overhead ti to have 2 versions if plugin if it works as is? It's just esm requires named cjs exports to work properly with cjs modules

I think you're right. Maybe we can export consistently of CJS and ESM in the next minor version. Adding  another export is good enough for now. Would like to revert to the prev version and make it merged. Thanks!

**Comment by wight554** [comment]
> I'm not sure if `export = plugin` is a valid ES syntax, if so, could you please paste a link for that?

It's valid for CJS, but yeah previous version was cleaner

**Comment by fi3ework** [comment]
> > I'm not sure if `export = plugin` is a valid ES syntax, if so, could you please paste a link for that?
> 
> It's valid for CJS, but yeah previous version was cleaner

We hope to resolve this in a more ESM flavor way as it's becoming more and more mainstream.

**Comment by wight554** [comment]
> revert to the prev version

Done

**Comment by fi3ework** [comment]
There's an extra semicolon that fails the CI 👀

**Comment by wight554** [comment]
> There's an extra semicolon that fails the CI 👀

fixed

**Comment by fi3ework** [comment]
https://github.com/fi3ework/vite-plugin-checker/blob/aaacf86fba50bed1d977c67e0491465e4830ee9c/packages/vite-plugin-checker/tsup.config.ts#L34

`'Plugin'` also should be changed to `checker`

**Comment by wight554** [comment]
> /packages/vite-plugin-checker/tsup.config.ts

done

**Review by fi3ework — APPROVED** [review]

**Pull request merged**
