### PR TITLE
refactor: import `@volar/typescript` from `vue-tsc`

### PR DESCRIPTION
**Pull request by so1ve**

### CODE REVIEW

**Comment by so1ve** [comment]
Nah. Ubuntu 20 tests failed

**Comment by fi3ework** [comment]
Adding a changeset please? Although it's a refactor but will make difference in userland.

**Comment by fi3ework** [comment]
CI is somehow not stable. It failed on ESLint, I've triggered retry and it should pass.

**Comment by so1ve** [comment]
I don't think it will cause any difference in userland. I've just removed a dependency that users don't have to install by themselves before.

**Comment by fi3ework** [comment]
It will make a difference in lockfile. Dependencies are fragile, especially in some large monorepo. Or some dependencies' consistence check.

**Comment by fi3ework** [comment]
Thank you! By the way, I've sponsored you on Afdian for your hard work, many thanks.

**Comment by so1ve** [comment]
Thanks, I really appreciate that. :heart:

**Pull request merged**
