### PR TITLE
feat: add basic support for Biome

### LINKED ISSUE #279: Biome support
### Is your feature request related to a problem? Please describe.

This is a feature request for [biome](https://biomejs.dev/).

Biome is a unified formatter / linter.

It was called rome.

### Describe the solution you'd like

I would like that I could see linter / formatting errors while running vite

### Describe alternatives you've considered

_No response_

### Additional context

old issue: https://github.com/fi3ework/vite-plugin-checker/issues/252

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by KurtGokhan**
Fixes #279

Mostly based on the ESLint checker.

I can add examples later. 

I tried to create an example in StackBlitz but [Biome doesn't work in StackBlitz for now](https://github.com/biomejs/biome/issues/1341).

[CodeSandbox example](https://codesandbox.io/p/devbox/4w7pfx)

### CODE REVIEW

**Comment by KurtGokhan** [comment]
@fi3ework  any concerns about this?

**Comment by momococomomo** [comment]
This is all that's holding us back from adopting Biome ATM. When will you merge this?

**Comment by yann-combarnous** [comment]
@fi3ework , any chance to merge this, maybe with an experimental `_unstable` prefix until there is more feedback?

**Comment by KurtGokhan** [comment]
As this is not getting merged, I am going to create a temporary fork and merge this there. I want to get out of ESlint ecosystem soon and this is blocking me.

**Comment by kamikazePT** [comment]
@KurtGokhan the failed tests, was it just a faulty run or is it broken in those scenarios? asking mostly because of node-20 ubuntu

**Comment by jhoermann** [comment]
> @KurtGokhan the failed tests, was it just a faulty run or is it broken in those scenarios? asking mostly because of node-20 ubuntu

@kamikazePT Tests are faulty for quite some time - see https://github.com/fi3ework/vite-plugin-checker/issues/264. Seems like they are getting fixed in PR https://github.com/fi3ework/vite-plugin-checker/pull/327.

**Comment by fi3ework** [comment]
Thanks @KurtGokhan for your contributing, and sorry for the long time to respond. I tweaked the code and it almost done. While there's something wrong when updating file diagnostic on Windows (I guess that's caused by the mix use of `absPath` and Biome's file.id. Could you help out if you're using a Window machine, or I'll take some time to grab a Windows machine next week. Thanks.

**Comment by KurtGokhan** [comment]
@fi3ework Thanks a lot for the updates. It looks much more polished now.

I noticed the issue now. Will try to fix it.

**Comment by KurtGokhan** [comment]
The issue should be fixed now.

Although now I think, it would be easier to just re-run Biome on all files on every file change, and it wouldn't even be noticeable because Biome is so fast. Maybe can add it as an option later.

**Comment by fi3ework** [comment]
> The issue should be fixed now.
> Although now I think, it would be easier to just re-run Biome on all files on every file change, and it wouldn't even be 
> noticeable because Biome is so fast. Maybe can add it as an option later.

If we could make it incremental and scalable now, we'd keep in this way. Full re-scan will take up all CPU resources (I guess, Biome will try to use the utmost resource it could), and that could cause a lag in user's device.

**Comment by fi3ework** [comment]
Thank you very much @KurtGokhan.

**Pull request merged**
