### PR TITLE
test: update win32 test serializer to work on any win32 machine

### PR DESCRIPTION
**Pull request by armano2**
This Pr fixes snapshot testing on windows machines that are not CI

ideally we would want to fix this issue upstream in [`jest-serializer-path`](https://github.com/tribou/jest-serializer-path/blob/master/lib/index.js), but this page seem to be no longer maintained

https://github.com/fi3ework/vite-plugin-checker/pull/327#issuecomment-2198006009

### CODE REVIEW

**Comment by armano2** [comment]
if you want we could just replace [jest-serializer-path](https://github.com/tribou/jest-serializer-path/blob/master/lib/index.js) with simpler serializer

**Comment by fi3ework** [comment]
If we could makes it work with a simple, promising script, we definitely could remove jest-serializer-path.

**Comment by armano2** [comment]
do you want me to update this PR, or submit it as separate one?

**Comment by fi3ework** [comment]
updating this PR is fine.

**Comment by armano2** [comment]
Looksike something like this is going to work, as a bonus Ubuntu 18 tests are passing now

**Comment by fi3ework** [comment]
Thank you! I'm AFK now, will take a look into the code when back later today.

**Review by fi3ework — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
